collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.8796992
color:
  saturation: 0.08113102
  brandStrength: 0.9985487
  lightness: 0.7367576
  brandColors:
    - '#030204'
    - '#5B5C61'
  rhythmicContrast: 0.5109597
layout_spectrum: 0.2907268
name: Imtheg-ddamnkwisachhaderach
