layout_spectrum: 0.3121639
typography_spectrum: 0.6671311
color:
  saturation: 0.08113102
  lightness: 0.7367576
  brandStrength: 0.9985487
  rhythmicContrast: 0.5109597
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: Imtheg-ddamnkwisachhaderach
