name: "I'm the G-ddamn Kwisatz Haderach"
favicon: null
layout_spectrum: 0.9824561
typography_spectrum: 0.8796992
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: "I'm the G-ddamn Kwisatz Haderach"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010302'
    - '#1E2938'
    - '#FFFCF2'
    - '#B4A391'
    - '#885C39'
  brandStrength: 1
  lightness: 0.188172
  saturation: 0.08113102
  rhythmicContrast: 0.5109597
purpose: []
