collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.08113102
  brandStrength: 1
  lightness: 0.7367576
  brandColors:
    - '#010302'
    - '#1E2938'
    - '#FFFCF2'
    - '#B4A391'
    - '#885C39'
  rhythmicContrast: 0.5109597
typography_spectrum: 0.8796992
layout_spectrum: 0.2907268
name: Imtheg-ddamnkwisatzhaderach
